### ISSUE TITLE
Expose stats on queue size

### ISSUE THREAD

**Issue by catenocrypt** [nanocurrency/nano-work-server#24]
For diagnostics purposes, it would be helpful to have statistics on the queue size, to expose the current queue size.
In a setup with large number of work generations it would help monitoring load, e.g. for decisions to increase/decrease amount of allocated resources.

A proposal is to expose it through a special command, like this:

```shell
curl -d '{"action":"nano_work_server_status"}' localhost:7076
```

```json
{
    "queue_size": 2
}
```

Statistics on average generation duration and count could be also helpful.

**Comment by guilhermelawless** [comment]
Seems reasonable, thanks for the suggestion!

**Comment by catenocrypt** [comment]
I have quickly created a solution for this, for my own usage; I will create a PR so you can decide if it OK for inclusion in this form.

https://github.com/catenocrypt/nano-work-server/tree/master
https://github.com/catenocrypt/nano-work-server/commit/fcfa8555527e030dc6c1c0a52e2e52a773dbd7a0

**Comment by guilhermelawless** [comment]
Looks great, just one suggestion and one request before you push a PR:
- Use simply the action "status" instead of "work_server_status"
- Please add the missing "benchmark" command to the hinted list of supported commands

**Comment by catenocrypt** [comment]
Done, #25 .
